#!/usr/bin/env python3
"""Installed-package integrity.

Two rules, and the second is the one that keeps being forgotten:

  1. Every file installed into a target must have a declared role, so nothing is
     shipped by accident and nothing is shipped whose resources are not shipped
     with it.
  2. Every installed verification entry point must actually run **in the target**.
     A source-tree test is not evidence about an installed package.

The canonical rule this module exists to enforce:

    SOURCE_TREE_PASS != INSTALLED_PACKAGE_PASS

For any packaging claim, the oracle must execute against the installed target.
The defect that motivated this: `tests/lib/edge_cases.py` was installed into
targets, but section D of that suite reads the repository's `examples/`
directory, which is not installed. The installed copy therefore aborted with
`FileNotFoundError` in every target while passing perfectly in the source tree.
A test that appears runnable and deterministically fails is worse than no test:
it trains the reader to ignore failures.

The chosen correction is to stop installing source-tree-only components, not to
ship the repository's example documents into every target. `edge_cases.py`
validates the repository's shipped examples, which is a repository-documentation
concern, and the installer already runs the suites that are target concerns.

Roles
-----
RUNTIME_REQUIRED             needed for the guard or the engine to work at all
TARGET_TEST_REQUIRED         a suite intended to run inside the target
DOCUMENTATION_REQUIRED       shipped to be read or copied, never executed
INTENTIONALLY_INSTALLED_DATA written or generated by the installer, not code

Anything installed that matches none of these is reported, so adding a file to
the installer without deciding its role fails the gate rather than silently
enlarging the installed surface.
"""

from __future__ import annotations

import ast
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))

GREEN = "\033[32m"
RED = "\033[31m"
YELLOW = "\033[33m"
RESET = "\033[0m"

ENGINE = ".verification"

# Prefix -> role. Longest prefix wins, so an exact path can override a directory.
ROLE_BY_PREFIX: list[tuple[str, str]] = [
    (f"{ENGINE}/bin/cdv", "RUNTIME_REQUIRED"),
    (f"{ENGINE}/core/cdv/", "RUNTIME_REQUIRED"),
    (f"{ENGINE}/core/templates/", "DOCUMENTATION_REQUIRED"),
    (f"{ENGINE}/schema/", "DOCUMENTATION_REQUIRED"),
    (f"{ENGINE}/VERSION", "INTENTIONALLY_INSTALLED_DATA"),
    (f"{ENGINE}/CLASSIFICATION", "INTENTIONALLY_INSTALLED_DATA"),
    (f"{ENGINE}/manifest.json", "INTENTIONALLY_INSTALLED_DATA"),
    (f"{ENGINE}/guard.config.json", "INTENTIONALLY_INSTALLED_DATA"),
    (f"{ENGINE}/.gitignore", "INTENTIONALLY_INSTALLED_DATA"),
    (f"{ENGINE}/tests/lib/canaries.py", "TARGET_TEST_REQUIRED"),
    (f"{ENGINE}/tests/lib/canary_runner.py", "TARGET_TEST_REQUIRED"),
    (f"{ENGINE}/tests/lib/static_checks.py", "TARGET_TEST_REQUIRED"),
    (f"{ENGINE}/tests/lib/context_canaries.py", "TARGET_TEST_REQUIRED"),
    (f"{ENGINE}/tests/e2e/enforcement_canary.py", "TARGET_TEST_REQUIRED"),
    (f"{ENGINE}/tests/independent_readback.py", "TARGET_TEST_REQUIRED"),
    (".opencode/plugin/verification-guard.ts", "RUNTIME_REQUIRED"),
]

# Files that are libraries for another installed entry point rather than entry
# points themselves. Everything else with a test role must run.
LIBRARY_STEMS = {"canaries.py"}

# How each runnable entry point is exercised inside the target. Each entry is a
# function of (target, repo, version) returning the argument list, so the
# invocation contract is explicit rather than guessed.
#
#   "run"    no arguments; must exit 0
#   "args"   arguments built below; must exit 0
#   "smoke"  needs something unavailable in a bare target (a model), so only
#            import and argument parsing are checked here; the end-to-end canary
#            is what runs it fully
#
# NOTE: shell_check.py and packaging_check.py are deliberately ABSENT. They check
# the repository's shell entry points and run the repository's installer, so they
# are source-tree-only and are not installed. Adding them here without installing
# them fails the declared-component check, which is the intended pressure: decide
# a component's role, and be consistent about it.
ENTRY_POINTS: dict[str, tuple[str, object]] = {
    "static_checks.py": ("run", None),
    "canary_runner.py": ("run", None),
    "context_canaries.py": ("run", None),
    # The readback tool compares an installation against its bootstrap source, so
    # it takes --source. INSTALL.md documents it that way, with /path/to/bootstrap.
    # A bare target is not a valid subject for it, and pretending otherwise is how
    # a check ends up testing its own invocation rather than the package.
    "independent_readback.py": (
        "args",
        lambda target, repo, version: [
            "--project", target, "--source", repo, "--expect-version", version
        ],
    ),
    "enforcement_canary.py": ("smoke", ["--help"]),
}

# Names that look like a local test-module import and therefore must be installed
# alongside whatever imports them.
LOCAL_MODULE_PREFIXES = ("canaries", "context_canaries", "static_checks")


def role_for(relative: str) -> str | None:
    best: tuple[int, str] | None = None
    for prefix, role in ROLE_BY_PREFIX:
        if relative == prefix or relative.startswith(prefix):
            if best is None or len(prefix) > best[0]:
                best = (len(prefix), role)
    return best[1] if best else None


def installed_files(target: str) -> list[str]:
    """Relative paths of every file the installer placed in the target."""
    found: list[str] = []
    for root in (os.path.join(target, ENGINE), os.path.join(target, ".opencode")):
        for directory, dirs, names in os.walk(root):
            dirs[:] = [d for d in dirs if d != "__pycache__"]
            for name in names:
                path = os.path.join(directory, name)
                found.append(os.path.relpath(path, target))
    return sorted(found)


def local_imports(path: str) -> set[str]:
    """Top-level module names the file imports, filtered to local-sounding ones."""
    try:
        tree = ast.parse(open(path, "r", encoding="utf-8").read(), filename=path)
    except (SyntaxError, OSError):
        return set()
    names: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                names.add(alias.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
            names.add(node.module.split(".")[0])
    return {n for n in names if n in LOCAL_MODULE_PREFIXES}


def check_install(target: str) -> list[str]:
    """Return findings; empty means the installed package is coherent."""
    findings: list[str] = []
    files = installed_files(target)

    # --- rule 1: every installed file has a declared role -------------------
    for relative in files:
        if role_for(relative) is None:
            findings.append(
                f"installed file has no declared role: {relative} — decide its role "
                "in packaging_check.ROLE_BY_PREFIX, or do not install it"
            )

    # --- rule 1b: declared components must actually be installed -----------
    for prefix, role in ROLE_BY_PREFIX:
        if role == "INTENTIONALLY_INSTALLED_DATA":
            continue
        if not any(f == prefix or f.startswith(prefix) for f in files):
            findings.append(f"declared component is missing from the install: {prefix} ({role})")

    # --- rule 1c: import closure is installed -------------------------------
    declared_stems = {os.path.basename(prefix) for prefix, _ in ROLE_BY_PREFIX}
    for relative in files:
        if not relative.endswith(".py"):
            continue
        for needed in local_imports(os.path.join(target, relative)):
            candidates = {f"{needed}.py"}
            if not (candidates & {os.path.basename(f) for f in files}):
                findings.append(
                    f"{relative} imports '{needed}', which is not installed "
                    "(installed module with an unmet dependency)"
                )
            elif needed not in {os.path.splitext(os.path.basename(s))[0] for s in declared_stems}:
                findings.append(f"{relative} imports '{needed}', which has no declared role")

    # --- rule 2: every installed entry point runs in the target ------------
    tests_lib = os.path.join(target, ENGINE, "tests", "lib")
    tests_e2e = os.path.join(target, ENGINE, "tests", "e2e")
    tests_root = os.path.join(target, ENGINE, "tests")
    version = open(os.path.join(target, ENGINE, "VERSION"), "r", encoding="utf-8").read().strip()

    for relative in files:
        basename = os.path.basename(relative)
        if basename in LIBRARY_STEMS or basename not in ENTRY_POINTS:
            continue
        mode, spec = ENTRY_POINTS[basename]
        directory = os.path.dirname(os.path.join(target, relative))
        command = [sys.executable, basename]
        if callable(spec):
            command += spec(target, REPO, version)
        elif spec:
            command += list(spec)
        proc = subprocess.run(
            command, cwd=directory, capture_output=True, text=True, timeout=600
        )
        output = (proc.stdout or "") + (proc.stderr or "")
        if mode == "smoke":
            # argparse exits 0 on --help; any import error shows as a traceback.
            broken = "Traceback" in output or "ModuleNotFoundError" in output
            if broken:
                findings.append(
                    f"installed entry point {relative} cannot even be loaded: "
                    + output.strip().splitlines()[-1][:200]
                )
            continue
        if proc.returncode != 0:
            last = output.strip().splitlines()[-1][:200] if output.strip() else "(no output)"
            findings.append(
                f"installed entry point {relative} failed in the target "
                f"(exit {proc.returncode}): {last}"
            )
        elif "FileNotFoundError" in output or "ModuleNotFoundError" in output:
            findings.append(
                f"installed entry point {relative} reported a missing packaged resource: "
                + output.strip().splitlines()[-1][:200]
            )
    return findings


def install_temp_target(quiet: bool = True) -> tuple[str, str]:
    """Create a disposable target and install into it. Returns (target, log_path)."""
    target = tempfile.mkdtemp(prefix="cdv-packaging-target-")
    subprocess.run(["git", "init", "-q"], cwd=target, capture_output=True)
    with open(os.path.join(target, "README.md"), "w", encoding="utf-8") as handle:
        handle.write("# disposable packaging target\n")
    subprocess.run(["git", "add", "-A"], cwd=target, capture_output=True)
    subprocess.run(
        ["git", "-c", "user.email=packaging@invalid", "-c", "user.name=packaging",
         "commit", "-qm", "init"],
        cwd=target, capture_output=True,
    )
    log_path = os.path.join(tempfile.gettempdir(), "cdv-packaging-install.log")
    installer = os.path.join(REPO, "installer", "install.sh")
    args = [installer, "--no-e2e", target]
    if quiet:
        args.insert(1, "--quiet")
    with open(log_path, "w", encoding="utf-8") as handle:
        subprocess.run(args, stdout=handle, stderr=subprocess.STDOUT, timeout=900)
    return target, log_path


def self_test() -> int:
    """Reproduce the original packaging defect and require it to be detected.

    Two scenarios, because the defect has two faces and a gate that catches only
    one of them is a gate that lets the other through.

      A1  the source-tree-only suite is installed without being declared
          -> caught by the role rule
      A2  the suite is installed AND declared, but the packaged resource it needs
          is absent -> caught by the execution rule

    A2 is the faithful reproduction: that is exactly how the defect shipped. The
    suite was installed, appeared runnable, and aborted with FileNotFoundError in
    every target because `examples/` was not installed with it.
    """
    print("=" * 78)
    print("PACKAGING CHECKER SELF-TEST (negative canary)")
    print("=" * 78)

    global ROLE_BY_PREFIX, ENTRY_POINTS
    saved_roles = list(ROLE_BY_PREFIX)
    saved_entries = dict(ENTRY_POINTS)
    failures: list[str] = []

    try:
        # --- A1: installed but undeclared ---------------------------------
        target, _ = install_temp_target()
        try:
            shutil.copy2(
                os.path.join(REPO, "tests", "lib", "edge_cases.py"),
                os.path.join(target, ENGINE, "tests", "lib", "edge_cases.py"),
            )
            findings = check_install(target)
            detected = [f for f in findings if "edge_cases.py" in f]
            if detected:
                print(f"  {GREEN}ok{RESET}   A1 installed-but-undeclared is detected:")
                print(f"         {detected[0][:150]}")
            else:
                failures.append("A1 installed-but-undeclared not detected")
                print(f"  {RED}FAIL{RESET} A1 installed-but-undeclared was NOT detected")
        finally:
            shutil.rmtree(target, ignore_errors=True)

        # --- A2: declared and installed, required resource absent ---------
        ROLE_BY_PREFIX = saved_roles + [
            (f"{ENGINE}/tests/lib/edge_cases.py", "TARGET_TEST_REQUIRED"),
        ]
        ENTRY_POINTS = dict(saved_entries)
        ENTRY_POINTS["edge_cases.py"] = ("run", None)
        target, _ = install_temp_target()
        try:
            shutil.copy2(
                os.path.join(REPO, "tests", "lib", "edge_cases.py"),
                os.path.join(target, ENGINE, "tests", "lib", "edge_cases.py"),
            )
            findings = check_install(target)
            executed = [
                f for f in findings
                if "edge_cases.py" in f and ("failed in the target" in f or "missing packaged resource" in f)
            ]
            if executed:
                print(f"  {GREEN}ok{RESET}   A2 declared-but-resource-absent is detected by execution:")
                print(f"         {executed[0][:150]}")
            else:
                failures.append("A2 declared-but-resource-absent not detected by execution")
                print(f"  {RED}FAIL{RESET} A2 was NOT detected by execution; findings were:")
                for item in findings:
                    print(f"         {item[:150]}")
        finally:
            shutil.rmtree(target, ignore_errors=True)
    finally:
        ROLE_BY_PREFIX = saved_roles
        ENTRY_POINTS = saved_entries

    print("-" * 78)
    if failures:
        print(f"PACKAGING_NEGATIVE_CANARY=FAIL ({len(failures)} scenario(s) undetected)")
        for item in failures:
            print(f"  - {item}")
        return 1
    print("PACKAGING_NEGATIVE_CANARY=FAIL_AS_DESIGNED")
    return 0


def main() -> int:
    if "--self-test" in sys.argv:
        return self_test()

    print("=" * 78)
    print("INSTALLED-PACKAGE INTEGRITY")
    print("=" * 78)
    print("Fresh install into a disposable target, then executed in that target.")
    print("A source-tree pass is not evidence about an installed package.")

    target, log_path = install_temp_target()
    try:
        files = installed_files(target)
        print(f"\ninstalled files: {len(files)}")
        roles: dict[str, int] = {}
        for relative in files:
            roles[role_for(relative) or "UNDECLARED"] = (
                roles.get(role_for(relative) or "UNDECLARED", 0) + 1
            )
        for role in sorted(roles):
            marker = f"{RED}UNDECLARED{RESET}" if role == "UNDECLARED" else role
            print(f"  {marker:32s} {roles[role]}")

        print("\nexecuting installed entry points in the target")
        findings = check_install(target)
        if not findings:
            print(f"  {GREEN}ok{RESET}   every installed entry point ran in the target")
        for item in findings:
            print(f"  {RED}FAIL{RESET} {item}")
    finally:
        shutil.rmtree(target, ignore_errors=True)
        if os.path.isfile(log_path):
            os.remove(log_path)

    print("-" * 78)
    if findings:
        print(f"INSTALLED_TEST_PACKAGING_GATE=FAIL ({len(findings)} finding(s))")
        return 1
    print("INSTALLED_TEST_PACKAGING_GATE=PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
